### ISSUE TITLE
How to send user/pass to the web interface

### ISSUE THREAD

**Issue by paul-price** [zylklab/alfresco-export-scripts#1]
The ReadMe file does not give an example of how to send an admin user account + pass to the site. I'd also like to see an example of a filled in web form.

**Comment by CesarCapillas** [comment]
Just check this:

https://github.com/zylklab/alfresco-export-scripts/blob/master/README.md#environment-vars

Regards.
--C.

**Comment by paul-price** [comment]
Hi Cesar.

I think I posted this to the wrong project. I am trying to use https://github.com/vprince1/alfresco-bulk-export.

Thanks,
Paul
